### ISSUE TITLE
Using PostgresDsn for database settings parsing broken on Pydantic 2.10.0 onward

### ISSUE THREAD

**Issue by attevaltojarvi** [erhosen-libs/pydjantic#35]
Hi,

after upgrading my Pydantic version to 2.10.x, I noticed that my Pydjantic settings for my project prevent it from starting up. This is my settings definition:

```
class DatabaseSettings(pydjantic.BaseDBConfig):
    default: t.Annotated[
        pydantic.PostgresDsn, pydantic.Field(
            validation_alias='DATABASE_URL',
            json_schema_extra={'test_options': {'MIGRATE': False}}
        )
    ]
    
class DjangoSettings(BaseSettings):
    DATABASES: DatabaseSettings = DatabaseSettings()
```

The crash happens in `django.db.utils`, in the `configure_settings` method, where the line `conn.setdefault("ATOMIC_REQUESTS", False)` raises `AttributeError: 'PostgresDsn' object has no attribute 'setdefault'`.

This seems to be due to a Pydantic internal change (I'm suspecting this PR: https://github.com/pydantic/pydantic/pull/10662), causing the `if not isinstance(value, (str, MultiHostUrl)):` check to be hit in the field validator method of the BaseDBConfig class, and the `value`, the PostgresDsn instance, being returned as-is. Apparently there's some inheritance change.

This can be prevented by importing the private base class from which PostgresDsn currently inherits from and adding it in the tuple:

```
from pydantic.networks import _BaseMultiHostUrl


class BaseDBConfig(BaseSettings):
    ...
    
    @field_validator('*')
    def format_config_from_dsn(cls, value: Any, info: ValidationInfo):
        if value is None:
            return {}

        if not isinstance(value, (str, MultiHostUrl, _BaseMultiHostUrl)):
            return value
    ....
```

but of course that's not an exhaustive solution.
